export const REQUEST_OPEN_FILE_1 = "request-open-file-1"
export const REQUEST_OPEN_FILE_2 = "request-garbled"
export const REQUEST_DIFFERENCE = "request-difference"
export const REQUEST_OPEN_SCHEDULE = "request-open-schedule"
export const REQUEST_SAVE_SCHEDULE = "request-save-schedule"
export const REQUEST_UPDATE_SCHEDULE = "request-update-schedule"

export const RESPONSE_OPEN_FILE_1 = "response-open-file-1"
export const RESPONSE_OPEN_FILE_2 = "response-open-file-2"
export const RESPONSE_DIFFERENCE = "response-difference"
export const RESPONSE_SCHEDULE = "response-schedule"
export const RESPONSE_SCHEDULE_SAVE = "response-schedule-save"